FROM twdps/circleci-remote-docker:slim-2023.05.1

LABEL org.opencontainers.image.title="circleci-base-image" \
      org.opencontainers.image.description="Debian-based CircleCI executor image" \
      org.opencontainers.image.documentation="https://github.com/ThoughtWorks-DPS/circleci-base-image" \
      org.opencontainers.image.source="https://github.com/ThoughtWorks-DPS/circleci-base-image" \
      org.opencontainers.image.url="https://github.com/ThoughtWorks-DPS/circleci-base-image" \
      org.opencontainers.image.vendor="ThoughtWorks, Inc." \
      org.opencontainers.image.authors="nic.cheneweth@thoughtworks.com" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created="CREATED" \
      org.opencontainers.image.version="VERSION"

ENV ONEPASSWORD_BETA_VERSION=2.18.0-beta.01
ENV ONEPASSWORD_VERSION=2.17.0-1
ENV TELLER_VERSION=1.5.6
ENV VAULT_VERSION=1.13.2
ENV BUILDEVENTS_VERSION=0.13.0
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# hadolint ignore=DL4001,DL3004,DL3047
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90circleci && \
    echo 'DPkg::Options "--force-confnew";' >> /etc/apt/apt.conf.d/90circleci && \
    apt-get update && apt-get install --no-install-recommends -y \
            sudo=1.9.13p3-1\
            locales=2.36-9 \
            curl=7.88.1-9 \
            wget=1.21.3-1+b2 \
            unzip=6.0-28 \
            gnupg=2.2.40-1.1 && \
    curl -L https://cache.agilebits.com/dist/1P/op2/pkg/v${ONEPASSWORD_BETA_VERSION}/op_linux_amd64_v${ONEPASSWORD_BETA_VERSION}.zip -o op.zip && \
    unzip -o op.zip && sudo mv op /usr/local/bin/op && \
    rm op.zip && rm op.sig && \
    curl -SLO https://github.com/ThoughtWorks-DPS/opw/releases/latest/download/opw_Linux_x86_64.tar.gz && \
    tar -xzf opw_Linux_x86_64.tar.gz && \
    sudo mv opw /usr/local/bin/opw && \
    curl -L https://github.com/tellerops/teller/releases/download/v${TELLER_VERSION}/teller_${TELLER_VERSION}_Linux_x86_64.tar.gz --output teller_${TELLER_VERSION}_Linux_x86_64.tar.gz && \
    tar -xzf teller_${TELLER_VERSION}_Linux_x86_64.tar.gz && \
    sudo mv teller /usr/local/bin/teller && \
    curl -SLO "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" > "vault_${VAULT_VERSION}_linux_amd64.zip" && \
    sudo unzip "vault_${VAULT_VERSION}_linux_amd64.zip" -d /usr/local/bin && \
    sudo rm "vault_${VAULT_VERSION}_linux_amd64.zip" && \
    curl -L -o buildevents https://github.com/honeycombio/buildevents/releases/download/v${BUILDEVENTS_VERSION}/buildevents-linux-amd64 && \
    chmod +x buildevents && \
    sudo mv buildevents /usr/local/bin/buildevents && \
    sudo apt-get remove unzip && \
    sudo apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen && \
    useradd --uid=3434 --user-group --create-home circleci && usermod --shell /bin/bash circleci && \
    echo 'circleci ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    sudo -u circleci mkdir /home/circleci/project

ENV PATH=/home/circleci/bin:/home/circleci/.local/bin:$PATH \
	 LANG=en_US.UTF-8 \
	 LANGUAGE=en_US:en \
	 LC_ALL=en_US.UTF-8

USER circleci

WORKDIR /home/circleci/project
